dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e './[dev]'
before_script:
  - coderedcms start testproject
# command to run tests
script:
  - python testproject/manage.py test coderedcms --settings=coderedcms.tests.settings
  - flake8 coderedcms
